### PR TITLE
add support for sass compilation

### PR DESCRIPTION
**Pull request by rsbroetto**
Hello!

I add a sass support (using node-sass package) into Svelte class and a options object to make it configurable.

### CODE REVIEW

**Comment by morpheus7CS** [comment]
Hey @rsbroetto,

thanks for contributing. Just FYI, I'll likely not get to this PR until Saturday. I'll let you know as soon as I go over it.

Kind regards,
g

**Comment by morpheus7CS** [comment]
Dear @rsbroetto,

I have thought about this for a very long time and decided not to merge the contribution. 

I do not consider myself an expert in Svelte. Therefore I would like to keep the "safety net" of having our interface closely mirror what Svelte is exposing as the best practice in their Webpack repository. 

This has two effects:
a) we always have a template we can go to for exploring what is missing and what else should be there; and
b) the developers actively developing in Svelte have a lot of community resources that can be mirrored to this project, without an additional learning curve.

Thank you again for your time and effort.

Kind regards,
g

**Comment by MattPurland** [comment]
Apologies for commenting on a closed issue, but not sure if this is well known or not. But this works fine based on the following method:

https://daveceddia.com/svelte-with-sass-in-vscode/

I had to install node-sass@4.14.1 (due to 5.0.0 having breaking changes), and with the following in my webpack.mix config:

```
const preprocess = require('svelte-preprocess');

.svelte({
        dev: !mix.inProduction(),
        preprocess: preprocess()
    });
```

**Comment by morpheus7CS** [comment]
@MattPurland no appoliogies needed! :)

**Pull request closed without merging**
